### ISSUE TITLE
Unable to generate - Poland (no state?)

### ISSUE THREAD

**Issue by FishandElmo** [louis-e/arnis#18]
No matter what I do I do not manage to generate a map of any city from Poland. I also don't know what to put in "state", I tried everything. I receive every time: "Error! No data available". It would be great if it was possible to generate without this parameter, or if you could explain to me how to do it.

python3 arnis.py --city "Białystok" --state "Podlaskie" --country "Polska" --path "D:/Pliki/world"
Fetching data...
Chosen server: https://lz4.overpass-api.de/api/interpreter
Error! No data available

**Comment by louis-e** [comment]
Hi there! Thanks for reaching out, try running the following command:
`python3 arnis.py --city "Białystok" --state "województwo podlaskie" --country "Polska" --path "D:/Pliki/world"`

The problem here is that OpenStreetMap has unique city / state / country names and if one of them isn't exactly the same as on OSM, it won't find the target. I used this site to figure out the exact name tag: https://www.openstreetmap.org/relation/224461#map=8/53.358/22.770

Another thing; I noticed that Białystok is quite a large city, so it'll probably take you a few hours to generate it. If you want to reduce the generation time for this case, try changing line 35 in getData.py to `way(area.country)(area.state)(area.city)[!power][!place][!ferry][!forestry][!railway][!denomination];`.

Good luck generating and keep me up to date if it worked! :)

**Comment by FishandElmo** [comment]
Thank you so much, it worked! What exactly will changing 35 line change?

**Comment by FishandElmo** [comment]
Btw after using the script, 10GB of space disappeared on my C drive, even though I have the script and the world from minecraft on my D drive. Can't locate where are the files what took the space. Can you help me?

**Comment by louis-e** [comment]
> Thank you so much, it worked! What exactly will changing 35 line change?

That's good to hear! :)
By changing that line, I'm excluding some more elements ([`!railway][!denomination][!boundary];`) from being generated. This reduces the world size as can be seen in the image below. I marked the generation size difference in purple. This improves the algorithm execution time a lot.
![image](https://github.com/louis-e/arnis/assets/44675238/a7fc6095-c11f-4fb5-a054-53218119e581)


> Btw after using the script, 10GB of space disappeared on my C drive, even though I have the script and the world from minecraft on my D drive. Can't locate where are the files what took the space. Can you help me?

Regarding your disk memory problem, I can imagine that Windows ran out of RAM memory during execution and distributed some data to a swap file on your C drive. That's a common process, usually after a few days or by restarting your computer the swap file size should be reduced again. Otherwise I can recommend the software TreeSize Free, it always helps me to locate big files and directories on my disks. Let me know if it worked!

**Comment by louis-e** [comment]
I'm going to close this issue as resolved for now, feel free to open it again if you need further help. Thanks!
