### ISSUE TITLE
[BUG] The new rust version again falls for the same out of memory errors

### ISSUE THREAD

**Issue by amir16yp** [louis-e/arnis#63]
**Describe the bug**
Runs out of memory when computing large maps. I think its the same as #8 except the problem is in rust. The solution would be to use memory-map files to store data instead of memory like i did in the python version in PR #30  
**Used bbox parameter**
34.549942,31.490310,34.651909,31.570931

**Screenshots**
![image](https://github.com/user-attachments/assets/7c60da52-085d-4357-bfce-d17c6315d071)

**Additional context**
Issue does not occur in the python version

**Comment by louis-e** [comment]
Hi there Amir, thanks for the notice! Besides a few minor bugs, this is the main thing I'm working on right now. I'm currently investigating what implementation approach is the best for this. Especially for finding a good balance between memory usage and performance. It's not quite easy to implement this feature since the element placement order does not follow a pattern which can be mapped to certain coordinate wise incremeting locations. But I'm certain, I can show off a first solution pretty soon! Already got something running right now.
I will use this Issue for keeping everyone up to date on this matter!

**Comment by louis-e** [comment]
Sorry for the late follow up, but this should've been solved by https://github.com/louis-e/arnis/pull/78 now! Just double checked it with your bbox parameter.
