### ISSUE TITLE
[BUG] there is no city after generation

### ISSUE THREAD

**Issue by defend-cmd** [louis-e/arnis#96]
after I generate a city in arnis, there is none in the world. I'm using version **1 12 2**. The world is unexplored. Please help me.

**Comment by louis-e** [comment]
Hi there, I see you closed this issue so I hope your problem is resolved now. It should always be generated starting from the Minecraft coordinates 0 0 0. :)

**Comment by eddir** [comment]
I encountered a similar issue previously. It turns out that the player often spawns at the zero coordinates, where there might not always be buildings or roads. This can happen due to the lack of OpenStreetMap data for that particular area. However, if you explore further from the spawn point, you should be able to find the generated structures.

I would also recommend creating a smaller-sized world to help ensure that the key areas are covered.
